import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Abel, ABeeZee } from "next/font/google";
import "./globals.css";
import { PopoverProvider } from "./context/PopoverContext";
import FilterContextProvider from "./context/FilterContext";

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
  style: ["normal"],
});

const abel = Abel({
  subsets: ["latin"],
  weight: "400",
  style: ["normal"],
});

const abeeZee = ABeeZee({
  subsets: ["latin"],
  weight: "400",
  style: ["italic", "normal"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${plusJakartaSans.variable} ${abel.className} ${abeeZee.className} antialiased`}
    >
      <body>
        <FilterContextProvider>
          <PopoverProvider>{children}</PopoverProvider>
        </FilterContextProvider>
      </body>
    </html>
  );
}
