import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { PopoverProvider } from "./context/PopoverContext";
import { GeoProvider } from "./context/GeoContext";
import FilterContextProvider from "./context/FilterContext";

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${plusJakartaSans.variable} antialiased`}>
        <GeoProvider>
          <FilterContextProvider>
            <PopoverProvider>{children}</PopoverProvider>
          </FilterContextProvider>
        </GeoProvider>
      </body>
    </html>
  );
}
